### ISSUE TITLE
const float[] argument passed to __device__ function does not work as expected

### ISSUE THREAD

**Issue by deven-amd** [RadeonOpenCompute/hcc#812] opened 2018-07-25 16:14 UTC
consider the following testcase
```
// main.cpp
#include <iostream>
#include <hip/hip_runtime.h>

template <typename Scalar, int N>
struct chebevl {
  static __host__ __device__ __inline__ Scalar run(Scalar x, const Scalar coef[]) {
    Scalar b0 = coef[0];
    Scalar b1 = 0;
    Scalar b2;

    for (int i = 1; i < N; i++) {
      b2 = b1;
      b1 = b0;
      b0 = x * b1 - b2 + coef[i];
    }

    return Scalar(0.5) * (b0 - b2);
  }
};

float cpu_kernel(float input) {

  const float B[] = {3.39623202570838634515E-9f, 2.26666899049817806459E-8f,
		     2.04891858946906374183E-7f, 2.89137052083475648297E-6f,
		     6.88975834691682398426E-5f, 3.36911647825569408990E-3f,
		     8.04490411014108831608E-1f};
  
  return chebevl<float, 7>::run(32.0f / input - 2.0f, B);
}

__global__ void gpu_kernel(hipLaunchParm lp, float* output, float* input) {

  const float B[] = {3.39623202570838634515E-9f, 2.26666899049817806459E-8f,
  		     2.04891858946906374183E-7f, 2.89137052083475648297E-6f,
  		     6.88975834691682398426E-5f, 3.36911647825569408990E-3f,
  		     8.04490411014108831608E-1f};

  int tid = threadIdx.x;
  float x = input[tid];
  output[tid] = chebevl<float, 7>::run(32.0f / x - 2.0f, B);
  //output[tid] = 42;
}

float gpu_kernel_caller(float input) {

  const int N = 16;
  auto memsize = N*sizeof(float);

  float* inputCPU = new float[N];
  float* outputCPU = new float[N];

  for (int i=0; i<N; i++) {
    inputCPU[i] = input;
    outputCPU[i] = -1;
  }
  float* inputGPU = nullptr;
  float* outputGPU = nullptr;
  
  hipError_t status = hipMalloc((void**)&inputGPU, memsize);
  if (status != hipSuccess) {
    std::cout << "call to hipMalloc (inputGPU) failed!" << std::endl;
  }

  status = hipMalloc((void**)&outputGPU, memsize);
  if (status != hipSuccess) {
    std::cout << "call to hipMalloc (outputGPU) failed!" << std::endl;
  }

  // copy input from host
  status = hipMemcpy(inputGPU, inputCPU, memsize, hipMemcpyHostToDevice);
  if (status != hipSuccess) {
    std::cout << "call to hipMemcpy (input) failed!" << std::endl;
  }

  // launch the kernel
  hipLaunchKernel(gpu_kernel, dim3(1), dim3(N), 0, 0, outputGPU, inputGPU);

  hipDeviceSynchronize();
  
  // copy output from device
  status = hipMemcpy(outputCPU, outputGPU, memsize, hipMemcpyDeviceToHost);
  if (status != hipSuccess) {
    std::cout << "call to hipMemcpy (output) failed!" << std::endl;
  }

  float answer = outputCPU[0];
  
  // free memory
  delete [] inputCPU;
  delete [] outputCPU;
  hipFree(inputGPU);
  hipFree(outputGPU);

  return answer;
}

int main() {

  float x = 20;
  
  float cpu_answer = cpu_kernel(x);
  float gpu_answer = gpu_kernel_caller(x);
  
  std::cout << "cpu_answer = " <<  cpu_answer << std::endl;
  std::cout << "gpu_answer = " <<  gpu_answer << std::endl;

  return 0;
}

```

The gpu_kernel returns an answer of `0` which is incorrect.

This is because the IR generated for it is incorrect.

```
; Function Attrs: alwaysinline norecurse nounwind
define weak_odr amdgpu_kernel void @_Z10gpu_kernelN8hip_impl17Empty_launch_parmEPfS1_(%"struct.std::less" %lp.coerce, float* %output, float* %input) #20 {
entry:
 %call.i = tail call i32 @hc_get_workitem_id(i32 0) #28
 %idxprom = sext i32 %call.i to i64
 %arrayidx = getelementptr inbounds float, float* %input, i64 %idxprom
 %0 = load float, float* %arrayidx, align 4, !tbaa !2972
 %div = fdiv float 3.200000e+01, %0
 %sub = fadd float %div, -2.000000e+00
 %mul.i = fmul float %sub, 0.000000e+00
 %add.i = fadd float %mul.i, 0.000000e+00
 %mul.1.i = fmul float %sub, %add.i
 %add.1.i = fadd float %mul.1.i, 0.000000e+00
 %mul.2.i = fmul float %sub, %add.1.i
 %sub.2.i = fsub float %mul.2.i, %add.i
 %add.2.i = fadd float %sub.2.i, 0.000000e+00
 %mul.3.i = fmul float %sub, %add.2.i
 %sub.3.i = fsub float %mul.3.i, %add.1.i
 %add.3.i = fadd float %sub.3.i, 0.000000e+00
 %mul.4.i = fmul float %sub, %add.3.i
 %sub.4.i = fsub float %mul.4.i, %add.2.i
 %add.4.i = fadd float %sub.4.i, 0.000000e+00
 %mul.5.i = fmul float %sub, %add.4.i
 %sub.5.i = fsub float %mul.5.i, %add.3.i
 %add.5.i = fadd float %sub.5.i, 0.000000e+00
 %sub2.i = fsub float %add.5.i, %add.3.i
 %mul3.i = fmul float %sub2.i, 5.000000e-01
 %arrayidx4 = getelementptr inbounds float, float* %output, i64 %idxprom
 store float %mul3.i, float* %arrayidx4, align 4, !tbaa !2972
 ret void
}
```

This error can be workedaround by changing the declaration of `B` in `gpu_kernel`

from 
```
const float B[] = ....
```
to
```
__device__ float B[] = ....
```

Please look into this and fix

deven

**Comment by whchung** [comment] 2018-07-25 16:57
additional info:

```
const float B[] = ...
```
has custom initializers missing

```
__device__ float B[] = ...
```
has correct custom intializers emitted

```
___device__ const float B[] = ...
```
has custom initializers missing

```
___device__ constexpr float B[] = ...
```
has custom initializers missing

```
___device__ constexpr float const B[] = ...
```
has custom initializers missing

**Comment by yxsamliu** [comment] 2018-07-25 17:33
I cannot reproduce the issue with hcc or hip-clang. In both case I got
cpu_answer = 0.40151
gpu_answer = 0.40151

clang emits IR like this for function-scope const array:
@_ZZ1fvE11const_array = private unnamed_addr addrspace(4) constant [5 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5], align 4

; Function Attrs: convergent noinline nounwind optnone
define void @_Z1fv() #0 {
entry:
  %const_array = alloca [5 x i32], align 4, addrspace(5)
  %0 = addrspacecast [5 x i32] addrspace(5)* %const_array to [5 x i32]*
  %1 = bitcast [5 x i32]* %0 to i8*
  call void @llvm.memcpy.p0i8.p4i8.i64(i8* align 4 %1, i8 addrspace(4)* align 4 bitcast ([5 x i32] addrspace(4)* @_ZZ1fvE11const_array to i8 addrspace(4)*), i64 20, i1 false)
  ret void
}

It emits a global variable in constant address space holding the initializer, and a stack variable, then it copies the constant var to the stack var by memcpy.

Are you using latest hcc?

**Comment by whchung** [comment] 2018-07-25 17:42
we are using hcc on rocm 1.8.2. we can definitely try with tip of HCC. it'd be great if it's solved in the tip of HCC already.

**Comment by whchung** [comment] 2018-07-25 19:07
confirmed tip of HCC + tip of HIP builds & runs this test fine. IR looks correct. @deven-amd pls give it a shot as well.

- `HIP` git commit #  73ef531
- `HCC` git commit #  d530be7

**Comment by whchung** [comment] 2018-07-27 21:11
closing this issue as it has been verified by @whchung and @deven-amd

**Closed as completed by whchung** 2018-07-27 21:11 UTC

**Comment by deven-amd** [comment] 2018-08-02 13:37
@sunway513 

@whchung how do we go about determining which commit / PR fixed this bug?  We need to figure out whether the fix is ROCM 1.9 for DL frameworks?

**Comment by whchung** [comment] 2018-08-02 15:17
@scchan @mangupta for awareness

we'll have to bisect but it'll take too much time.

I'd recommend HIP and HCC team to make sure 1.9 release branches contains all commits prior to the previous working config I found:

HIP git commit # 73ef531
HCC git commit # d530be7

**Comment by scchan** [comment] 2018-08-02 15:23
1.9 was branched earlier and it's kind of late to merge all the extra commits into 1.9 right now.  Do you know if the current 1.9 branch works? https://github.com/RadeonOpenCompute/hcc/tree/roc-1.9.x

**Comment by whchung** [comment] 2018-08-02 15:27
@scchan let me give it a quick spin

**Comment by whchung** [comment] 2018-08-02 15:54
@scchan / @deven-amd good news. tip of HCC roc-1.9.x and tip of HIP roc-1.9.x works fine :)

HCC git commit # 08aa7f8
HIP git commit # 6584918

**Comment by scchan** [comment] 2018-08-02 16:26
great, thanks for testing it
