### ISSUE TITLE
ds_read_b32 2nd VGPR Incorrect in Inline Assembly

### ISSUE THREAD

**Issue by jlgreathouse** [RadeonOpenCompute/hcc#693] opened 2018-04-16 22:02 UTC
I have a small test application (a modified version the 'square' HIP example) that attempts to use shared memory from inline assembly. This is a reproducer showing the same problem as reported by a customer whose code I can't give out.

The kernel attempts to insert a `ds_read_b32` assembly instruction using an inline assembly statement:
```__asm__ volatile("ds_read_b32 %0 %1\ns_waitcnt lgkmcnt(0)" : "=v"(outputter) : "v"(&localMem[i]));```

When attempting to compile this kernel, it fails because the compiler attempts to put a pair of registers into %1:
```
$ make
/opt/rocm/hip/bin/hipcc  square.cpp -o square.out
<inline asm>:1:17: error: invalid operand for instruction
        ds_read_b32 v5 v[5:6]
                       ^
note: !srcloc = 1858
Generating AMD GCN kernel failed in llc for target: gfx803
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/hip/bin/hipcc line 501.
Makefile:13: recipe for target 'square.out' failed
make: *** [square.out] Error 1
```

Adding a more stringent input constraint to %1 bypasses the error:
```__asm__ volatile("ds_read_b32 %0 %1\ns_waitcnt lgkmcnt(0)" : "=v"(outputter) : "{v1}"(&localMem[i]));```
```
$ make
/opt/rocm/hip/bin/hipcc  square.cpp -o square.out
$ ./square.out
info: running on device Fiji [Radeon R9 FURY / NANO Series]
info: allocate host mem (  0.00 MB)
info: allocate device mem (  0.00 MB)
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
Row 0: 1234
Row 1: 1235
Row 2: 1236
Row 3: 1237
Row 4: 1238
Row 5: 1239
Row 6: 1240
Row 7: 1241
Row 8: 1242
Row 9: 1243
```

Information about the system setup:
- Radeon RX Vega 56 (gfx900)
- Also observed on Radeon R9 Nano (gfx803)
- Using the same inline assembly within an OpenCL kernel *does not* cause the same problem.

```
$ hcc --version
HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang ac8732c272d3ce6a4d1ee6aa636f06d44cd5170c) (ssh://gerritgit/compute/ec/hcc-tot/llvm 710f135c41925e12aa088c26e1a9f583b1778fbe) (based on HCC 1.2.18063-7e18c64-ac8732c-710f135 )
$ dkms status
rock, 1.7.137-ubuntu, 4.4.0-116-generic, x86_64: installed
$ clinfo | grep Driver
  Driver version:                                2576.0 (HSA1.1,LC)
```

Reproducer code:
[modified_square.tar.gz](https://github.com/RadeonOpenCompute/hcc/files/1917452/modified_square.tar.gz)

**Comment by scchan** [comment] 2018-04-17 21:06
The issue is that the `ds_read_b32` instruction takes an 32-bit offset from the beginning of the DS section rather than an actual pointer (e.g. `&localMem[i]`), which is always 64-bit generic pointer in hcc.

A possible workaround would be to call a builtin function defined in our device library to convert a generic pointer into an equivalent of an OpenCL pointer to local memory.  

First define the prototype of the pointer conversion builtin:
`extern "C"  __attribute__((address_space(3))) void* __to_local(void* p) [[hc]];`

Change
`__asm__ volatile("ds_read_b32 %0 %1\ns_waitcnt lgkmcnt(0)" : "=v"(outputter) : "v"(&localMem[i]));`

into

` __asm__ volatile("ds_read_b32 %0 %1\ns_waitcnt lgkmcnt(0)" : "=v"(outputter) : "v"(__to_local(&localMem[i])));`

I'd suggest that you open an issue against HIP to either expose this builtin or to provide a better solution.

**Comment by scchan** [comment] 2018-06-27 14:34
feature request for HIP therefore closing this issue

**Closed as completed by scchan** 2018-06-27 14:34 UTC
