### ISSUE TITLE
Couldn't build HCC clang_tot_upgrade branch on Ubuntu 16.04-arm64 server with gcc 5.4.0

### ISSUE THREAD

**Issue by lintcoder** [RadeonOpenCompute/hcc#465] opened 2017-09-19 01:46 UTC
I am trying to build ROCm from branch roc-1.6.3 on my ubunu16.04-arm64 server which is running on Cavium Thunder X. Now I have built ROCK-Kernel-Driver, ROCT-Thunk-Interface and ROCR-Runtime.
When it comes to HCC, I follow the steps in repo RadeonOpenCompute/hcc:
1.git clone --recursive -b clang_tot_upgrade https://github.com/RadeonOpenCompute/hcc.git
Now hcc is on branch clang_tot_upgrade
2.cd hcc
3.mkdir build; cd build
4.cmake -DNUM_BUILD_THREADS=96 -DCMAKE_BUILD_TYPE=Release ..
Output of cmake as follows(something omitted)
ROCm INFORMATION:
HSA_HEADER_DIR = , actually found at: /usr/local/include
HSA_LIBRARY_DIR = , actually found at: /usr/local/lib/libhsa-runtime64.so
ROCM_DEVICE_LIB_DIR = /home/cavium/rocm/hcc/rocdl
Installation path: /opt/rocm/hcc-1.0
Installer package installation path: /opt/rocm/hcc-1.0

HCC version: 1.0.17262-e8cf396-e8cf396-e8cf396

-- HCC configured with AMDGPU targets: auto
-- ROCm available, going to build HSA HCC Runtime
-- build HCC CPU Runtime
For the first time:
'make' to build all
'make docs' to build the HTML API reference

-- Configuring done
-- Generating done
-- Build files have been written to: /home/cavium/rocm/hcc/build
5. make -j96
Output as follows(something omitted)
error: unable to create target: 'No available targets are compatible with this triple.'
error: unable to create target: 'No available targets are compatible with this triple.'
2 errors generated.
lib/CMakeFiles/mcwamp_atomic.dir/build.make:62: recipe for target 'lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o' failed
make[2]: *** [lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o] Error 1
CMakeFiles/Makefile2:106730: recipe for target 'lib/CMakeFiles/mcwamp_atomic.dir/all' failed
make[1]: *** [lib/CMakeFiles/mcwamp_atomic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
......
[ 92%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/atanpiredH.cl
[ 92%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/copysignF.cl
[ 92%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/rintD.cl
error: unable to create target: 'No available targets are compatible with this triple.'
error: unable to create target: 'No available targets are compatible with this triple.'
2 errors generated.
[ 98%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/i0H.cl
[ 98%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/isnanF.cl
error: unable to create target: 'No available targets are compatible with this triple.'
error: unable to create target: 'No available targets are compatible with this triple.'
2 errors generated.
amp-conformance/CMakeFiles/amptest.dir/build.make:86: recipe for target 'amp-conformance/CMakeFiles/amptest.dir/amp_test_lib/src/device.cpp.o' failed
make[2]: *** [amp-conformance/CMakeFiles/amptest.dir/amp_test_lib/src/device.cpp.o] Error 1
CMakeFiles/Makefile2:107207: recipe for target 'amp-conformance/CMakeFiles/amptest.dir/all' failed
make[1]: *** [amp-conformance/CMakeFiles/amptest.dir/all] Error 2
...........
[ 98%] Linking OCL static library ocml.lib.bc
Generating ocml.amdgcn.bc
[ 98%] Built target ocml_lib
[ 98%] Linking OCL static library opencl.lib.bc
WARNING: Linking two modules of different data layouts: 'transformed_src/workgroup/wgscratch.ll' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5'

[ 98%] Built target libclang
Generating opencl.amdgcn.bc
[ 98%] Built target opencl_lib
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

@whchung

**Comment by whchung** [comment] 2017-09-19 02:34
@lintcoder since it's a new platform I would expect some weird issue could arise, especially when Clang Driver is try deal with target triples. could you capture your build log with this `CMake` command?

` cmake .. -DCMAKE_CXX_FLAGS="-v"`

this should allow more insights on why we are seeing this `No available targets are compatible with this triple`

**Comment by whchung** [comment] 2017-09-19 02:38
some places I can quickly think of are `x86-64`-specific, and may need to be switched to your host architecture.

- `lib/clamp-embed.in` : `objcopy` is used to rename a section inside a kernel object file.
- `lib/clamp-link.in` : `clang-offload-bundler` is invoked and use `x86-64`-specific string to identify host objects.
- `lib/extractkernel.in` : same as above.

**Comment by lintcoder** [comment] 2017-09-20 00:54
@whchung thanks for your advice, here is my build log with "-DCMAKE_CXX_FLAGS="-v":
........
Scanning dependencies of target mcwamp_atomic
[ 97%] Building CXX object lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o
HCC clang version 6.0.0  (based on HCC 1.0.17373-bd1f35c-c639ce0-e4adac0 )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cavium/rocm/hcc/build/compiler/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Candidate multilib: .;@ m64
Selected multilib: .;@ m64
 "/home/cavium/rocm/hcc/build/compiler/bin/clang-6.0" -cc1 -D__KALMAR_AMP__=1 -D__HCC_AMP__=1 -D__KALMAR_CPU__=1 -D__HCC_CPU__=1 -triple aarch64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name mcwamp_atomic.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=line-tables-only -dwarf-version=4 -debugger-tuning=gdb -v -coverage-notes-file /home/cavium/rocm/hcc/build/lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.gcno -resource-dir /home/cavium/rocm/hcc/build/compiler/lib/clang/6.0.0 -isystem /home/cavium/rocm/hcc/utils -D GTEST_HAS_TR1_TUPLE=0 -I /home/cavium/rocm/hcc/build/include -I /home/cavium/rocm/hcc/include -I /home/cavium/rocm/hcc/compiler/include -I /home/cavium/rocm/hcc/build/lib -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /home/cavium/rocm/hcc/build/compiler/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fdebug-compilation-dir /home/cavium/rocm/hcc/build/lib -ferror-limit 19 -fmessage-length 135 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o -x c++ /home/cavium/rocm/hcc/lib/mcwamp_atomic.cpp
clang -cc1 version 6.0.0 based upon HCC 1.0.17373-bd1f35c-c639ce0-e4adac0  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0"
#include "..." search starts here:
#include <...> search starts here:
 /home/cavium/rocm/hcc/build/include
 /home/cavium/rocm/hcc/include
 /home/cavium/rocm/hcc/compiler/include
 /home/cavium/rocm/hcc/build/lib
 /home/cavium/rocm/hcc/utils
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/local/include
 /home/cavium/rocm/hcc/build/compiler/lib/clang/6.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
error: unable to create target: 'No available targets are compatible with this triple.'
error: unable to create target: 'No available targets are compatible with this triple.'
2 errors generated.
make[2]: *** [lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o] Error 1
lib/CMakeFiles/mcwamp_atomic.dir/build.make:62: recipe for target 'lib/CMakeFiles/mcwamp_atomic.dir/mcwamp_atomic.cpp.o' failed
make[1]: *** [lib/CMakeFiles/mcwamp_atomic.dir/all] Error 2
CMakeFiles/Makefile2:106730: recipe for target 'lib/CMakeFiles/mcwamp_atomic.dir/all' failed
make: *** [all] Error 2
Makefile:149: recipe for target 'all' failed

I would like to know how can I fix the problem and those x86-64 -specific things as you mentioned.

**Comment by whchung** [comment] 2017-09-20 01:25
Please try change those lines I mentioned earlier from x86-64 to aarch64-

**Comment by lintcoder** [comment] 2017-09-20 03:05
@whchung I have tried your method while it seems no help

**Comment by whchung** [comment] 2017-09-20 04:10
@lintcoder it's failing at this line:
https://github.com/RadeonOpenCompute/hcc-clang-upgrade/blob/clang_tot_upgrade/lib/CodeGen/BackendUtil.cpp#L700

let me do some investigation about this.

**Comment by lintcoder** [comment] 2017-09-22 01:16
@whchung thanks, it would be very helpful,  and I wonder if there is any progress?

**Comment by lintcoder** [comment] 2017-09-25 02:36
@whchung I see you have made some commits last Friday, are these modifications helpful to fix the build problem?

**Comment by whchung** [comment] 2017-09-25 03:55
@lintcoder nope, those commits won't help building on aarch64 yet. I'm getting an aarch64-based system hopefully by Monday my time so I can dig into this issue and make sure host path of `hcc` works with aarch64 architecture.

**Comment by whchung** [comment] 2017-10-02 16:58
@lintcoder sorry for being late on this topic. I've finally secured an aarch64-based system so I'll be working on this issue and keep you posted.

**Comment by lintcoder** [comment] 2017-10-09 01:09
@whchung sorry for replying so late, since I had been on vacation for these days. I am glad to hear that you've gotten an aarch64-based system in hand, and if you have any progress on this topic, please let me know, many thanks.

**Comment by whchung** [comment] 2017-10-16 19:23
@lintcoder I've made some progress in this ticket. ll be start pushing some commits to `aarch64` branch so you can try reproduce my results.

**Comment by whchung** [comment] 2017-10-16 21:08
@lintcoder initial `aarch64` port is at: https://github.com/RadeonOpenCompute/hcc/tree/aarch64 . I'm still working with kernel/runtime team to validate this port. will keep you posted.

**Comment by lintcoder** [comment] 2017-10-17 07:50
@whchung I've updated my local repo to aarch64 port, and change several submodules branches as follows:
clang to aarch64 branch, 
clang-tools-extra to amd-hcc branch, 
compiler to amd-hcc branch, 
compiler-rt to amd-hcc branch, 
lld to amd-hcc branch 
rocdl to 0d09c00

then I try to build it with multi-thread, some of output are here:
[ 91%] Building OCL object rocdl/ocml/CMakeFiles/ocml_lib.dir/src/fpclassifyD.cl
In file included from /home/cavium/rocm/hcc/lib/hsa/hc_am.cpp:9:
/usr/local/include/hsa/hsa.h:93:2: error: "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
#error "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
 ^
[ 91%] Linking OCL static library ockl.lib.bc
......
[ 91%] Building OCL object rocdl/opencl/CMakeFiles/opencl_lib.dir/src/media/sadhi.cl
1 error generated.
lib/hsa/CMakeFiles/hc_am.dir/build.make:62: recipe for target 'lib/hsa/CMakeFiles/hc_am.dir/hc_am.cpp.o' failed
make[2]: *** [lib/hsa/CMakeFiles/hc_am.dir/hc_am.cpp.o] Error 1
CMakeFiles/Makefile2:110313: recipe for target 'lib/hsa/CMakeFiles/hc_am.dir/all' failed
make[1]: *** [lib/hsa/CMakeFiles/hc_am.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
......
[100%] Linking OCL static library opencl.lib.bc
WARNING: Linking two modules of different data layouts: 'transformed_src/workgroup/wgscratch.ll' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5'

Generating opencl.amdgcn.bc
[100%] Built target opencl_lib
[100%] Linking CXX static library ../lib/libamptest.a
[100%] Built target amptest
[100%] Linking CXX static library ../../lib/libmcwamp_gtest.a
[100%] Built target mcwamp_gtest
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I would like to know that if the branch I used in these submodules is right to build this repo, and I am looking forward to your upcoming progress.

**Comment by whchung** [comment] 2017-10-17 13:39
@lintcoder the branches you are using are correct. to save you some time, you can use `git checkout aarch64; git submodule update` to make sure all submodules are in the correct configuration.

there are some changes in kernel/thunk/runtime required to cope with `aarch64` which are not inside `hcc`. I'm going to post them in the next few replies.

**Comment by whchung** [comment] 2017-10-17 14:32
@lintcoder several topics you need to be aware of:

1) CPU endianness

```
/usr/local/include/hsa/hsa.h:93:2: error: "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
#error "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
```

please manually change `/opt/rocm/include/hsa/hsa.h`. I assume the machine you are using is little endian by default.

```
// Try to detect CPU endianness
#if !defined(LITTLEENDIAN_CPU) && !defined(BIGENDIAN_CPU)
#if defined(__i386__) || defined(__x86_64__) || defined(_M_IX86) || \
-    defined(_M_X64)
+    defined(_M_X64) || defined(__aarch64__)
#define LITTLEENDIAN_CPU
#endif
#endif

```

I'm going to submit a PR again `ROCR-Runtime` on this change.

---

2) headers in `/usr/include`

I found i have to create several symlinks under `/usr/include`:
- `/usr/include/sys -> /usr/include/aarch64-linux-gnu/sys`
- `/usr/include/gnu -> /usr/include/aarch64-linux-gnu/gnu`
- `/usr/include/bits -> /usr/include/aarch64-linux-gnu/bits`
- `/usr/include/asm -> /usr/include/aarch64-linux-gnu/asm`

On `x86` systems `g++-multilib` package fixes this but i don't see such package on `aarch64` architecture so currently I do it manually.

Upon completing step 1) and 2) you shall be able to build `hcc` on your `aarch64` system.

---

3) manually set PCIe atomics configuration

Also, you will need to override PCIe atomics setting on your system so it's possible for ROCR runtime to capture completion signal when a kernel completes:

```
sudo setpci -v -s 0005:8f:00.0 98.b=60
```

To my understanding, `0005:8f:00.0` is the address of the PCIe bridge. On `x86` systems we don't need this, and i assume a BIOS change may be required.

A vanilla C-based test, `simple_dispatch`, could be found at: https://gist.github.com/whchung/79b92141d7274e0b3dda20b688db21aa

You can download it, build it, and run it. Before setting `setpci` it would hang. But after invoking `setpci` it would run to completion. Notice it contains an empty kernel for `gfx803` AMD GPU. If you use a `gfx900` AMD GPU such as Vega, please let me know.

Upon completing this step you shall be able to dispatch kernels to AMD GPUs.

---

4) ROCm Agent Enumerator, `--amdgpu-target`

This is a tool used by `hcc` at link-time, to determine what AMD GPUs are installed on the system. It traverses PCIe bus and collect relevant information. It's distributed inside `rocm-util` package and I think it doesn't have `aarch64` port yet.

To get around with this limitation, once you are able to finish building `hcc`, you can try build HCC test programs with explicitly specifying `--amdgpu-target=` flag. For example, on my test `aarch64` system I have an AMD R9 Nano installed, which is of `gfx803` family. So I can build and run  a test program with:

```
export PATH=/opt/rocm/hcc/bin:$PATH
hcc `hcc-config --cxxflags --ldflags` tests/Unit/AmpMath/amp_math_cos.cpp --amdgpu-target=gfx803
./a.out; echo $?
```

---

5) nuisances at runtime:

You will see various warning messages at runtime, they are harmless though. I'm working with kernel/runtime team to address them.

a) when ROCR runtime initializes:
```
Failed to get Processor Vendor. Setting to GenuineIntel
```
This is a warning raised in KFD Thunk library. 

b) Warning in signal wait

```
Warning: !g_use_interrupt_wait && "Use of non-host signal in host signal wait API." in virtual hsa_signal_value_t core::DefaultSignal::WaitRelaxed(hsa_signal_condition_t, hsa_signal_value_t, uint64_t, hsa_wait_state_t), /home/whchung/ROCm/ROCR-Runtime/src/core/runtime/default_signal.cpp:91
```
Getting this warning when waiting on a signal, although it doesn’t seem to affect runtime behavior.


Add @hthangirala for awareness.

**Comment by whchung** [comment] 2017-10-17 18:44
@lintcoder also I'd like to let you that I've verified following `hcc`-based tools/applications now work on my `aarch64`-based system:

- `HIP`: https://github.com/ROCm-Developer-Tools/HIP
- `rocBLAS`: https://github.com/ROCmSoftwarePlatform/rocBLAS

**Comment by lintcoder** [comment] 2017-10-18 08:32
@whchung thanks for your detailed reply first. Since I've made symlinks before, after making changes in hsa.h, I build hcc successfully. While I got an error when setting PCIe atomics configuration, my AMD GPU card is RX460:
sudo setpci -v -s 0005:8f:00.0 98.b=60
setpci: Warning: No devices selected for "98.b=60".

what's more, I build HIP:https://github.com/ROCm-Developer-Tools/HIP successfully, but there is something weird during cmake process as follows:

cmake -DHSA_PATH=/opt/rocm/hsa -DHCC_HOME=/opt/rocm/hcc-1.0 -DCMAKE_INSTALL_PREFIX=/opt/rocm/hip -DCMAKE_BUILD_TYPE=Release ..
......
hipify-clang will not be built. To build it please specify absolute path to LLVM 3.8 or LLVM 3.9 package/dist using -DHIPIFY_CLANG_LLVM_DIR
......

I would like to know if it will have an impact on using hip.

**Comment by whchung** [comment] 2017-10-18 14:42
@lintcoder good to hear that. some answers/comments:

1) address for the PCI bridge:

`0005:8f:00.0` is the address of the PCI bridge my AMD GPU talks to. please find the correct address on your system via `lspci -vv | grep "PCI bridge"`. there could be several on your system, and you should check to which PCI bridge your AMD GPU is connected.

2) warning message for `hipify-clang`

you can ignore it as long as you don't use that tool to automatically convert `.cu` to `.cpp`.

3) RX460

RX460 is a different chip (Polaris11) than RX470/RX480 (Polaris10), and I think AMD ships a different BIOS with it. From compiler standpoint they share the same GCN insturction set `gfx803`, but I'm not sure whether ROCm kernel/runtime would be able to correctly dispatch GPU kernels on this model.

You are encouraged to try `simple_dispatch` I posted at:
https://gist.github.com/whchung/79b92141d7274e0b3dda20b688db21aa

**Comment by whchung** [comment] 2017-10-20 14:28
@lintcoder I'm hereby closing this ticket as compilation problem of `hcc` is resolved. please feel free to create new tickets in runtime issue.

**Closed as completed by whchung** 2017-10-20 14:28 UTC

**Comment by 0hanghang** [comment] 2020-03-18 04:15
@whchung @lintcoder how did you build HIP on ARM64 platform .I compile it from HIP master branch and I got :
[100%] Built target lpl
fatal error: error in backend: Unsupported calling convention.
fatal error: error in backend: Unsupported calling convention.
fatal error: error in backend: Unsupported calling convention.
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
HCC clang version 11.0.0 (https://github.com/RadeonOpenCompute/llvm-project c32999245deae93c525dceb4974b7a74dc0ab42a) (based on HCC 3.1.20105-fb10f75b-c32999245de )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
clang-11: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
CMakeFiles/hip_hcc_static.dir/build.make:278: recipe for target 'CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
HCC clang version 11.0.0 (https://github.com/RadeonOpenCompute/llvm-project c32999245deae93c525dceb4974b7a74dc0ab42a) (based on HCC 3.1.20105-fb10f75b-c32999245de )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
clang-11: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
CMakeFiles/hip_hcc.dir/build.make:350: recipe for target 'CMakeFiles/hip_hcc.dir/src/hip_module.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc.dir/src/hip_module.cpp.o] Error 70
make[2]: *** Waiting for unfinished jobs....
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
HCC clang version 11.0.0 (https://github.com/RadeonOpenCompute/llvm-project c32999245deae93c525dceb4974b7a74dc0ab42a) (based on HCC 3.1.20105-fb10f75b-c32999245de )
Target: aarch64-unknown-linux-gnu

any help ? thank you in advance!

**Comment by 0hanghang** [comment] 2020-03-18 04:16
beside cmake -DHSA_PATH=/usr/local/hsa -DHCC_HOME=/opt/rocm/hcc -DCMAKE_INSTALL_PREFIX=/opt/rocm/hip -DCMAKE_PREFIX_PATH=/home/ubuntu/opencl/rocm/ROCm-CompilerSupport/lib/comgr/build/lib/cmake/amd_comgr/ -DCMAKE_BUILD_TYPE=Release ..
