### ISSUE TITLE
Passing user defined half datatype as hipLaunchParm to a templated kernel causing AMD GCN kernel failure

### ISSUE THREAD

**Issue by NEELMCW** [RadeonOpenCompute/hcc#668] opened 2018-03-28 10:40 UTC
Hello team,

Below is my standalone test code . Upon compilation with hipcc hit the following error 

errorlog:
1 warning generated.
Instruction does not dominate all uses!
  %20 = extractvalue { i1, i64 } %18, 1
  call void @llvm.amdgcn.end.cf(i64 %20)
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx803
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/hip/bin/hipcc line 501.

CODE SNIPPET:  
[test_custom_half_kernel.cpp.txt](https://github.com/RadeonOpenCompute/hcc/files/1855632/test_custom_half_kernel.cpp.txt)

**Comment by scchan** [comment] 2018-03-28 19:54
I was able to reproduce it and it looks like to be an issue in the GCN backend.  I've opened an internal ticket to track this.

**Comment by NEELMCW** [comment] 2018-03-30 09:11
I tried passing half with the basic square hip example . I was able to build it but hit a runtime hang.
HIP_TRACE_API=1 does confirm that the kernel has launched successfully. That hang is experienced after call to hipMemcpy of device results back to host .

PFA the files .. Below is the log that I get after seeing HIP_TRACE_API for these files

[half.hpp.txt](https://github.com/RadeonOpenCompute/hcc/files/1863186/half.hpp.txt)
[square.cpp.txt](https://github.com/RadeonOpenCompute/hcc/files/1863187/square.cpp.txt)


Runtime Log:

HIP_DB=0x1 [api]
  hip-api tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7f18b3cfc800)
<<hip-api tid:1.1 hipGetDeviceProperties (0x7ffef68bc858, 0) @1388966412030155
  hip-api tid:1.1 hipGetDeviceProperties         ret= 0 (hipSuccess)>> +3640 ns
info: running on device Fiji [Radeon R9 FURY / NANO Series]
info: allocate host mem (  3.81 MB)
info: allocate device mem (  3.81 MB)
<<hip-api tid:1.2 hipMalloc (0x7ffef68bca10, 2000000) @1388966423627303
  hip-api tid:1.2 hipMalloc                      ret= 0 (hipSuccess)>> +23685 ns
<<hip-api tid:1.3 hipMalloc (0x7ffef68bca08, 2000000) @1388966423696444
  hip-api tid:1.3 hipMalloc                      ret= 0 (hipSuccess)>> +167358 ns
info: copy Host2Device
<<hip-api tid:1.4 hipMemcpy (0x50200e000, 0x7f18ae92a010, 2000000, hipMemcpyHostToDevice) @1388966423884271
  hip-api tid:1.4 hipMemcpy                      ret= 0 (hipSuccess)>> +620217 ns
info: launch 'vector_square' kernel
<<hip-api tid:1.5 hipModuleLaunchKernel (0x502005000, 512, 1, 1, 256, 1, 1, 0, stream:<null>, 0, 0x7ffef68bc630) @1388966424542225
<<hip-api tid:1.5 1.5 hipLaunchKernel '_Z13vector_squareI4halfEvRPT_S3_m' gridDim:{131072,1,1} groupDim:{256,1,1} sharedMem:+0 stream:0.0 @1388966424550651
  hip-api tid:1.5 hipModuleLaunchKernel          ret= 0 (hipSuccess)>> +40024 ns
info: copy Device2Host
<<hip-api tid:1.6 hipMemcpy (0x7f18ae569010, 0x502400000, 2000000, hipMemcpyDeviceToHost) @1388966424592292

**Comment by NEELMCW** [comment] 2018-05-09 06:22
@scchan  any updates on this ?

**Comment by scchan** [comment] 2018-05-09 14:51
We've posted a fix and it's being reviewed: https://reviews.llvm.org/D46340

**Comment by scchan** [comment] 2018-06-27 14:38
@NEELMCW The latest hcc already has the fix, have you got a chance to verify it?

**Comment by NEELMCW** [comment] 2018-06-28 11:55
Hello SiuChi,

Yes , I was able to build kernels with half parameters now . But many of
them in our CNTK port hangs indefinitely. HIP_TRACE_API shows hipFree to be
last call which hasn't returned a success code

**Comment by scchan** [comment] 2018-08-20 14:57
closing since the fix for the compilation issue is already in the compiler

**Closed as completed by scchan** 2018-08-20 14:57 UTC
